ARG CONTAINER_REGISTRY=harbor.cmt.apps.telenet.be
FROM ${CONTAINER_REGISTRY}/quay/quarkus/quarkus-micro-image:2.0
ARG APP=**/target/*-runner
WORKDIR /work/

COPY ${APP} /work/application
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
